/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmc.minecraft;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import javax.swing.JOptionPane;
import jmc.minecraft.utils.ConfigLoaderCore;

import jmc.minecraft.utils.GlobalVar;
import jmc.minecraft.utils.Utils;



/**
 *
 * @author DimanA90
 */
public class Options extends javax.swing.JDialog {
    //public class Options extends javax.swing.JFrame {
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupClientType = new javax.swing.ButtonGroup();
        jFileChooserSelectDir = new javax.swing.JFileChooser();
        PanelOptions = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ButtonOpenClientDir = new javax.swing.JButton();
        ButtonForseUpdate = new javax.swing.JButton();
        jPanelClientType = new javax.swing.JPanel();
        jRadioButtonDefault = new javax.swing.JRadioButton();
        jRadioButtonPortable = new javax.swing.JRadioButton();
        jRadioButtonInstalled = new javax.swing.JRadioButton();
        jTextFieldInstPath = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CheckBoxExpertSettings = new javax.swing.JCheckBox();
        jLabelJavaPath = new javax.swing.JLabel();
        jTextFieldJavaPath = new javax.swing.JTextField();
        jLabeArguments = new javax.swing.JLabel();
        jTextFieldJavaArguments = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHelp = new javax.swing.JTextArea();
        jButtonSaveSettings = new javax.swing.JButton();

        jFileChooserSelectDir.setAcceptAllFileFilterUsed(false);
        jFileChooserSelectDir.setDialogTitle("Выберете папку куда будет установлен лаунчер со всеми компонентами");
        jFileChooserSelectDir.setFileHidingEnabled(true);
        jFileChooserSelectDir.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Настройки");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Клиент"));

        ButtonOpenClientDir.setText("Открыть папку текущего клиента");
        ButtonOpenClientDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonOpenClientDirMouseClicked(evt);
            }
        });

        ButtonForseUpdate.setText("Принудительно обновить текущий клиент");
        ButtonForseUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonForseUpdateMouseClicked(evt);
            }
        });
        ButtonForseUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonForseUpdateActionPerformed(evt);
            }
        });

        jPanelClientType.setBorder(javax.swing.BorderFactory.createTitledBorder("Тип клиента"));

        buttonGroupClientType.add(jRadioButtonDefault);
        jRadioButtonDefault.setText("По умолчанию");
        jRadioButtonDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDefaultActionPerformed(evt);
            }
        });

        buttonGroupClientType.add(jRadioButtonPortable);
        jRadioButtonPortable.setText("Портативный");
        jRadioButtonPortable.setToolTipText("");
        jRadioButtonPortable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPortableActionPerformed(evt);
            }
        });

        buttonGroupClientType.add(jRadioButtonInstalled);
        jRadioButtonInstalled.setText("Установлен в:");
        jRadioButtonInstalled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonInstalledActionPerformed(evt);
            }
        });

        jTextFieldInstPath.setEditable(false);

        jButtonBrowse.setText("Обзор");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientTypeLayout = new javax.swing.GroupLayout(jPanelClientType);
        jPanelClientType.setLayout(jPanelClientTypeLayout);
        jPanelClientTypeLayout.setHorizontalGroup(
            jPanelClientTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPortable)
                    .addComponent(jRadioButtonDefault)
                    .addGroup(jPanelClientTypeLayout.createSequentialGroup()
                        .addComponent(jRadioButtonInstalled)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldInstPath, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBrowse)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelClientTypeLayout.setVerticalGroup(
            jPanelClientTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientTypeLayout.createSequentialGroup()
                .addComponent(jRadioButtonDefault)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPortable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInstPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonInstalled)
                    .addComponent(jButtonBrowse))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelClientType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonOpenClientDir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonForseUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonOpenClientDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonForseUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelClientType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        ConfigLoaderCore cf = new ConfigLoaderCore();
        cf.LoadModeConfig();
        if(GlobalVar.LauncherMode.contains("default")){
            jRadioButtonDefault.setSelected(true);
            jTextFieldInstPath.setEnabled(false);
            jButtonBrowse.setEnabled(false);
        }else if(GlobalVar.LauncherMode.contains("portable")){
            jRadioButtonPortable.setSelected(true);
            jTextFieldInstPath.setEnabled(false);
            jButtonBrowse.setEnabled(false);
        }else if(GlobalVar.LauncherMode.contains("installed")){
            jRadioButtonInstalled.setSelected(true);
            jTextFieldInstPath.setEnabled(true);
            jTextFieldInstPath.setText(GlobalVar.LauncherStandalonePath);
            jButtonBrowse.setEnabled(true);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Расширенная настройка для выбранного клиента игры"));

        CheckBoxExpertSettings.setText("Использовать");
        CheckBoxExpertSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxExpertSettingsActionPerformed(evt);
            }
        });

        jLabelJavaPath.setText("Путь до java:");

        jTextFieldJavaPath.setToolTipText("Например C:\\Program Files\\Java\\jre7\\bin\\java.exe\nЕсли в пути имеются пробелы то всю строку необходимо заключить в ковычки, перед каждой ковычкой обязательноставить обратный слеш \\\"");

        jLabeArguments.setText("Аргументы:");
        jLabeArguments.setToolTipText("Команды для инициализации ява машины");

        jTextFieldJavaArguments.setText("-Xms512m -Xmx512m");

        jTextAreaHelp.setEditable(false);
        jTextAreaHelp.setColumns(20);
        jTextAreaHelp.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextAreaHelp.setRows(5);
        jTextAreaHelp.setText("Некторые команды для аргументов:\n-Xms Пример -Xms256m или в гигабайтах -Xms1G\nhttp://www.minecraftforum.net/topic/1874325-jvm-argument-fps-boost/");
        jScrollPane1.setViewportView(jTextAreaHelp);

        jButtonSaveSettings.setText("Сохранить настройки");
        jButtonSaveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJavaPath)
                            .addComponent(jLabeArguments))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldJavaArguments)
                            .addComponent(jTextFieldJavaPath)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CheckBoxExpertSettings)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jButtonSaveSettings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckBoxExpertSettings)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJavaPath)
                    .addComponent(jTextFieldJavaPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeArguments)
                    .addComponent(jTextFieldJavaArguments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSaveSettings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CheckBoxExpertSettings.setSelected(GlobalVar.ExpertSettings);
        jTextFieldJavaPath.setEnabled(CheckBoxExpertSettings.isSelected());
        jTextFieldJavaArguments.setEnabled(CheckBoxExpertSettings.isSelected());
        jLabeArguments.setEnabled(CheckBoxExpertSettings.isSelected());
        jLabelJavaPath.setEnabled(CheckBoxExpertSettings.isSelected());
        jTextAreaHelp.setEnabled(CheckBoxExpertSettings.isSelected());
        jButtonSaveSettings.setEnabled(CheckBoxExpertSettings.isSelected());
        jTextFieldJavaPath.setText(GlobalVar.JavaPath);
        jTextFieldJavaArguments.setText(GlobalVar.JavaVMArg);

        javax.swing.GroupLayout PanelOptionsLayout = new javax.swing.GroupLayout(PanelOptions);
        PanelOptions.setLayout(PanelOptionsLayout);
        PanelOptionsLayout.setHorizontalGroup(
            PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PanelOptionsLayout.setVerticalGroup(
            PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonForseUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonForseUpdateMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ButtonForseUpdateMouseClicked

    private void ButtonOpenClientDirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonOpenClientDirMouseClicked
        // TODO add your handling code here:
        try{
        Utils.openLink(new URL("file://" + Utils.getWorkingDirectory().getAbsolutePath() + File.separator + GlobalVar.itemsServers[GlobalVar.CurrentServer] + File.separator).toURI() );
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_ButtonOpenClientDirMouseClicked

    private void CheckBoxExpertSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxExpertSettingsActionPerformed
        // TODO add your handling code here:
        if(CheckBoxExpertSettings.isSelected()){
            JOptionPane.showMessageDialog( null,
                    "Если вы используете эти опции и у Вас перестала работать игра то это проблема кривости Ваших рук и невнимательности!\nЛаунчер не виноват что Вы не умеете пользоваться этими настройками.",
                    "!!! ПРЕДУПРЕЖДЕНИЕ !!!",
                    JOptionPane.WARNING_MESSAGE);
        }else{
        GlobalVar.ExpertSettings = CheckBoxExpertSettings.isSelected();
        ConfigLoaderCore cfg = new ConfigLoaderCore();
        cfg.saveCurrentClientConfig();
        }
        jTextFieldJavaPath.setEnabled(CheckBoxExpertSettings.isSelected());
        jTextFieldJavaArguments.setEnabled(CheckBoxExpertSettings.isSelected());
        jLabeArguments.setEnabled(CheckBoxExpertSettings.isSelected());
        jLabelJavaPath.setEnabled(CheckBoxExpertSettings.isSelected());
        jTextAreaHelp.setEnabled(CheckBoxExpertSettings.isSelected());
        jButtonSaveSettings.setEnabled(CheckBoxExpertSettings.isSelected());
    }//GEN-LAST:event_CheckBoxExpertSettingsActionPerformed

    private void jButtonSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSettingsActionPerformed
        // TODO add your handling code here:
        GlobalVar.ExpertSettings = CheckBoxExpertSettings.isSelected();
        GlobalVar.JavaPath = jTextFieldJavaPath.getText();
        GlobalVar.JavaVMArg = jTextFieldJavaArguments.getText();
        ConfigLoaderCore cfg = new ConfigLoaderCore();
        cfg.saveCurrentClientConfig();
                
    }//GEN-LAST:event_jButtonSaveSettingsActionPerformed

    private void ButtonForseUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonForseUpdateActionPerformed
        // TODO add your handling code here:
        Utils.ForseUpdate();
    }//GEN-LAST:event_ButtonForseUpdateActionPerformed

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        // TODO add your handling code here:
        int returnVal = jFileChooserSelectDir.showOpenDialog(this);
    if (returnVal == jFileChooserSelectDir.APPROVE_OPTION) {
        File file = jFileChooserSelectDir.getSelectedFile();
        try {
          // What to do with the file, e.g. display it in a TextArea
            GlobalVar.LauncherStandalonePath = file.getAbsolutePath()+File.separator;  //Заносим путь в глобалку
            GlobalVar.LauncherMode = "installed";
            ConfigLoaderCore cf = new ConfigLoaderCore();
            
            
            cf.saveModeConfig();
            
            
          jTextFieldInstPath.setText(file.getAbsolutePath());
          
          ShowInfoToRestart();
        } catch (Exception ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jRadioButtonDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDefaultActionPerformed
        // TODO add your handling code here:
        DeleteModeConf();
            jTextFieldInstPath.setEnabled(false);
            jButtonBrowse.setEnabled(false);
        ShowInfoToRestart();
        
    }//GEN-LAST:event_jRadioButtonDefaultActionPerformed

    private void jRadioButtonPortableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPortableActionPerformed
        // TODO add your handling code here:
        GlobalVar.LauncherMode = "portable";
        ConfigLoaderCore cf = new ConfigLoaderCore();
            cf.saveModeConfig();
            jTextFieldInstPath.setEnabled(false);
            jButtonBrowse.setEnabled(false);
        ShowInfoToRestart();
    }//GEN-LAST:event_jRadioButtonPortableActionPerformed

    private void jRadioButtonInstalledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonInstalledActionPerformed
        // TODO add your handling code here:
        jTextFieldInstPath.setEnabled(true);
        jButtonBrowse.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonInstalledActionPerformed
private void DeleteModeConf(){
    String path = (new File(Options.class.getProtectionDomain().getCodeSource().getLocation().getPath())).getAbsolutePath();
    File file = new File(path.substring(0, path.length()-4)+".json");
    if (file.exists()) file.delete();
    
}
private void ShowInfoToRestart(){
    JOptionPane.showMessageDialog( null,
                    "Лаунчер будет закрыт для применения новых настроек.",
                    "Применение настроек",
                    JOptionPane.WARNING_MESSAGE);
    System.exit(1);
}
    /**
     * Creates new form Options
     */
    public Options() {
        
        initComponents();
        CheckBoxExpertSettings.setSelected(GlobalVar.ExpertSettings);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonForseUpdate;
    private javax.swing.JButton ButtonOpenClientDir;
    private javax.swing.JCheckBox CheckBoxExpertSettings;
    private javax.swing.JPanel PanelOptions;
    private javax.swing.ButtonGroup buttonGroupClientType;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonSaveSettings;
    private javax.swing.JFileChooser jFileChooserSelectDir;
    private javax.swing.JLabel jLabeArguments;
    private javax.swing.JLabel jLabelJavaPath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelClientType;
    private javax.swing.JRadioButton jRadioButtonDefault;
    private javax.swing.JRadioButton jRadioButtonInstalled;
    private javax.swing.JRadioButton jRadioButtonPortable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaHelp;
    private javax.swing.JTextField jTextFieldInstPath;
    private javax.swing.JTextField jTextFieldJavaArguments;
    private javax.swing.JTextField jTextFieldJavaPath;
    // End of variables declaration//GEN-END:variables
}
